# Generated by Django 6.0.6 on 2026-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('water', 'Water Wastage'), ('e_waste', 'E-Waste'), ('solid_waste', 'Solid/Garbage Waste'), ('animal_injury', 'Injured/Sick Animal')], max_length=20)),
                ('location', models.CharField(help_text='Area in Ahmedabad', max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
