# Generated by Django 6.0.6 on 2026-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_photos/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('water', 'Water Wastage'), ('e_waste', 'E-Waste'), ('solid_waste', 'Solid/Garbage Waste'), ('animal_injury', 'Injured/Sick Animal'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
