# Generated by Django 6.0.6 on 2026-06-26 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_image_alter_complaint_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hazard_type', models.CharField(choices=[('plastic', 'Accumulated Plastic / Garbage Dump'), ('ewaste', 'Electronic / Chemical Waste'), ('water', 'Stagnant Water / Drainage Leak'), ('animal_risk', 'High Wildlife/Stray Injury Risk Zone')], max_length=20)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_cleared', models.BooleanField(default=False)),
            ],
        ),
    ]
