# Generated by Django 6.0.6 on 2026-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_wastelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_24_7', models.BooleanField(default=False)),
                ('open_time', models.CharField(default='09:00 AM', max_length=50)),
                ('close_time', models.CharField(default='08:00 PM', max_length=50)),
            ],
        ),
    ]
